behaviors:
  BoatAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.04
        gamma: 0.99
        learning_rate: 3.0e-4
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    checkpoint_interval: 50000
    keep_checkpoints: 25